### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by 13retonnian** [FesalBadday/blackjack#2]
Aces can be either 1 or 11 in blackjack.
On Dissenter browser all of the letters at the top are jammed together with no spaces.
The <title></title> is mispelled as balckjack.
Card goes over top of text box when hovered.
The sign in and sign up page look exactly the same so it's hard to tell which page I'm on.
I can move the box around that contains the bets.
Played a lot and game froze on the make bet screen.

**Comment by FesalBadday** [comment]
That's right Aces can be either 1 or 11 depends on whichever makes a better hand. Good catch for the title, will work on the other stuff. Thanks

**Comment by Raj-Hunjan** [comment]
Hey Fesal maybe you should space out the rules so it's a bit easier to read.

**Comment by FesalBadday** [comment]
> Hey Fesal maybe you should space out the rules so it's a bit easier to read.

Will do that. Thank you

**Comment by FesalBadday** [comment]
Fixed. Thanks
